# Generated by Django 6.0.3 on 2026-03-24 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('desc', models.TextField(max_length=100, verbose_name='text')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1453), django.core.validators.MinValueValidator(-756)], verbose_name='year')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='pub date')),
            ],
        ),
    ]
